config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'shops#index'
  resources :users, only: :show
  resources :shops do
    resources :evaluation_comments, only: [:create, :destroy]
    member do
      get 'search'
    end
    collection do
      get 'fashion'
      get 'food'
      get 'interior'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evaluation_comment.rb
class EvaluationComment < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :title,   presence: true, length: { minimum: 1, maximum: 30, allow_blank: true}
  validates :content, length: { minimum: 1, maximum: 300, allow_blank: true}
  validates :rate,    numericality: { less_than_or_equal_to: 5, greater_than_or_equal_to: 0.5, message: "最低でも0.5以上の評価が必要です"}
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '大阪府' },
  ]

  include ActiveHash::Associations
  has_many :shops

  end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :evaluation_comments, dependent: :destroy
  has_many_attached :images

  validates :images,       presence: true
  validates :shop_genre_id, numericality: { other_than: 1, message: "can't be blank" } 
  validates :shop_name,    presence: true, length: { minimum: 1, maximum: 30, allow_blank: true}
  validates :introduction, presence: true, length: { minimum: 1, maximum: 300, allow_blank: true}
  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" } 
  validates :shop_city_id, numericality: { other_than: 1, message: "can't be blank" } 
  validates :shop_address, length: { minimum: 1, maximum: 40, allow_blank: true}

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :shop_genre
  belongs_to :shop_city
  belongs_to :prefecture

  def self.search(search)
    if search != ""
      Shop.where('shop_name LIKE(?)', "%#{search}%")
    else
      render :index
    end
  end
end

app/models/shop_city.rb
class ShopCity < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '大阪市都島区' }, { id: 3, name: '大阪市福島区' },
    { id: 4, name: '大阪市此花区' }, { id: 5, name: '大阪市西区' }, { id: 6, name: '大阪市港区' },
    { id: 7, name: '大阪市大正区' }, { id: 8, name: '大阪市天王寺区' }, { id: 9, name: '大阪市浪速区' },
    { id: 10, name: '大阪市西淀川区' }, { id: 11, name: '大阪市東淀川区' }, { id: 12, name: '大阪市東成区' },
    { id: 13, name: '大阪市生野区' }, { id: 14, name: '大阪市旭区' }, { id: 15, name: '大阪市城東区' },
    { id: 16, name: '大阪市阿倍野区' }, { id: 17, name: '大阪市住吉区' }, { id: 18, name: '大阪市東住吉区' },
    { id: 19, name: '大阪市西成区' }, { id: 20, name: '大阪市淀川区' }, { id: 21, name: '大阪市鶴見区' },
    { id: 22, name: '大阪市住之江区' }, { id: 23, name: '大阪市平野区' }, { id: 24, name: '大阪市北区' },
    { id: 25, name: '大阪市中央区' }, { id: 26, name: '堺市堺区' }, { id: 27, name: '堺市中区' },
    { id: 28, name: '堺市東区' }, { id: 29, name: '堺市西区' }, { id: 30, name: '堺市南区' },
    { id: 31, name: '堺市北区' }, { id: 32, name: '堺市美原区' }, { id: 33, name: '岸和田市' },
    { id: 34, name: '豊中市' }, { id: 35, name: '池田市' }, { id: 36, name: '吹田市' },
    { id: 37, name: '泉大津市' }, { id: 38, name: '高槻市' }, { id: 39, name: '貝塚市' },
    { id: 40, name: '守口市' }, { id: 41, name: '枚方市' }, { id: 42, name: '茨木市' },
    { id: 43, name: '八尾市' }, { id: 44, name: '泉佐野市' }, { id: 45, name: '富田林市' },
    { id: 46, name: '寝屋川市' }, { id: 47, name: '河内長野市' }, { id: 48, name: '松原市' },
    { id: 49, name: '大東市' }, { id: 50, name: '和泉市' }, { id: 51, name: '箕面市' },
    { id: 52, name: '柏原市' }, { id: 53, name: '羽曳野市' }, { id: 54, name: '門真市' },
    { id: 55, name: '摂津市' }, { id: 56, name: '高石市' }, { id: 57, name: '藤井寺市' },
    { id: 58, name: '東大阪市' }, { id: 59, name: '泉南市' }, { id: 60, name: '四條畷市' },
    { id: 61, name: '交野市' }, { id: 62, name: '大阪狭山市' }, { id: 63, name: '阪南市' },
    { id: 64, name: '三島郡島本町' }, { id: 65, name: '豊能郡豊能町' }, { id: 66, name: '豊能郡能勢町' },
    { id: 67, name: '泉北郡忠岡町' }, { id: 68, name: '泉南郡熊取町' }, { id: 69, name: '泉南郡田尻町' },
    { id: 70, name: '泉南郡岬町' }, { id: 71, name: '泉南郡太子町' }, { id: 72, name: '南河内郡河南町' },
    { id: 73, name: '南河内郡千早赤阪村' },
  ]

  include ActiveHash::Associations
  has_many :shops

  end

  

app/models/shop_genre.rb
class ShopGenre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'Fashion' },
    { id: 3, name: 'Food' },
    { id: 4, name: 'Interior' },
  ]

  include ActiveHash::Associations
  has_many :shops

  end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops
  has_many :evaluation_comments

  validates :username, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数字で設定してください'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/evaluation_comments_controller.rb
class EvaluationCommentsController < ApplicationController
  def create
    @comment = EvaluationComment.new(comment_params)
    @shop = Shop.find(params[:shop_id])
    if @comment.save
      redirect_to shop_path(id: @shop.id) 
    else
      @evaluation_comments = @shop.evaluation_comments.includes(:user).order("created_at DESC")
      render template: "shops/show"
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @comment = EvaluationComment.find(params[:id])
    @comment.destroy
    redirect_to shop_path(id: @shop.id) 
  end

  private
  def comment_params
    params.require(:evaluation_comment).permit(:title, :content, :rate).merge(user_id: current_user.id, shop_id: params[:shop_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :genre, only: [:index, :fashion, :food, :interior]
  before_action :common, only: [:show, :edit, :update, :destroy]

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = EvaluationComment.new
    @comments = EvaluationComment.where(params[:shop_id])
    @evaluation_comments = @shop.evaluation_comments.includes(:user).order("created_at DESC")
  end 

  def edit
    unless @shop.user.id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(id: @shop.id)
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to root_path
  end

  def search
    @shops = Shop.search(params[:keyword])
  end

  private

  def genre
    @fashion = Shop.where(shop_genre_id:2).order("created_at DESC")
    @food = Shop.where(shop_genre_id:3).order("created_at DESC")
    @interior = Shop.where(shop_genre_id:4).order("created_at DESC")
  end

  def common
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit({images:[]}, :shop_genre_id, :shop_name, :introduction, :prefecture_id, :shop_city_id, :shop_address, :evaluation).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @user = user
    @shops = user.shops
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluation_comments_helper.rb
module EvaluationCommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Osakawalker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <%# トップページのスライダー %>
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

  </head>

  <body>
    <%= yield %>
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
    <%= link_to image_tag("OsakaWalker LOGO.jpg", class:"logo-white"), root_path %> 
  <p>Copyright © OSAKA WALKER All rights reserved.</p>
</div>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <div class="headline">
    <h2>大阪のお洒落なお店がシェアできる・見つかるウェブサイト</h2>
  </div>
  <div class="header-main">
    <div class="nav">
        <%= link_to image_tag("OsakaWalker LOGO.jpg", class: :logo), root_path %>
      <div class="nav__center">
        <ul class="nav__list">
          <li class="nav_link">
            <%= link_to "FASHION", fashion_shops_path %>
            <%# fashion ドロップダウンメニュー %>
            <ul class="dropdown__lists">
              <%# <%= link_to "Amekaji/", "#", class: :dropdown__list %>
            </ul>
          </li>
          <li class="nav_link">
            <%= link_to "FOOD", food_shops_path %>
            <%# food ドロップダウンメニュー %>
            <ul class="dropdown__lists">
              <%# <%= link_to "Washoku/", "#", class: :dropdown__list %>
            </ul>
          </li>
          <li class="nav_link">
            <%= link_to "INTERIOR", interior_shops_path %>
            <%# interior ドロップダウンメニュー %>
            <ul class="dropdown__lists">
              <%# <%= link_to "Modern/", "#", class: :dropdown__list %>
            </ul>
          </li>
        </ul>
      </div>
      
      <%# ログイン有無で表示切り替え %>
      <% if user_signed_in? %>
      <div class="nav__right"> 
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :logout__btn %>
        <%= link_to "New Shop", new_shop_path, class: :shop__btn %>
      </div> 
      <% else %>
      <div class="nav__right">
        <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
        <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
      </div>
      <% end %>

    </div>
  </div>
</header>

app/views/shops/edit.html.erb
<div class="shops-contents">
  <header class="shops-post-header">
    <%= link_to image_tag('OsakaWalker LOGO.jpg' , size: '300x80'), root_path %>

  </header>
  <div class="shops-post-main">
    <h2 class="shops-post-title">ショップ情報を編集</h2>
    <%= form_with model: @shop, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# ショップ画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        ショップ画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, id:"shop-image", multiple: true %>
      </div>
    </div>
    <%# /ショップ画像 %>

    <%# ショップのジャンル %>
    <div class="shops-genre">
      <div class="weight-bold-text">
        ショップジャンル
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:shop_genre_id, ShopGenre.all, :id, :name, {}, {class:"select-box", id:"shop-genre"}) %>
    </div>
    <%# /ショップのジャンル %>

    <%# ショップ名と説明 %>
    <div class="new-shops">
      <div class="weight-bold-text">
        ショップ名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :shop_name, class:"shops-text", id:"shop_name", placeholder:"ショップ名（必須 30文字まで)", maxlength:"40" %>
      <div class="shops-explain">
        <div class="weight-bold-text">
          ショップの説明など
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"shops-text", id:"introduction", placeholder:"ショップの説明など（必須 300文字まで）（テイストや特徴、アクセス手段など自由可）" ,rows:"7" ,maxlength:"300" %>
      </div>
    </div>
    <%# /ショップ名と説明 %>

    <%# ショップの所在地 %>
    <div class="shops-place">
      <div class="weight-bold-text">
        <span>ショップ所在地</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"shop-prefectures"}) %>
        <div class="weight-bold-text">
          市区町村
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shop_city_id, ShopCity.all, :id, :name, {},  {class:"select-box", id:"shop-city"}) %>
        <div class="weight-bold-text">
          それ以降
          <span class="optional">任意</span>
        </div>
        <%= f.text_area :shop_address, class:"shops-text", id:"shop_address", placeholder:"(任意)", maxlength:"40" %>
      </div>
    </div>
    <%# /ショップの所在地 %>

    <%# 下部ボタン %>
    <div class="post-btn-contents">
      <%= f.submit "編集を完了する" ,class:"post-btn" %>
      <%=link_to '削除する', shop_path(@shop.id), method: :delete, class:"delete-btn", data: {confirm: "削除しますか？"} %>
      <%=link_to 'キャンセル', shop_path(@shop.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<script>
  const post = document.getElementsByClassName('post-btn');
  const posts = Array.from(post);

  posts.forEach(function(postss) {
    postss.addEventListener('click', function() {
      window.alert('変更が正常に行われました。');
    });
  });
</script>

<%= render "shared/footer" %>

app/views/shops/fashion.html.erb
<%= render "shared/header" %>

<div class="eachshop-main">
  <h2 class="list-title">
    FASHION SHOP LIST
  </h2>
  <div class="eachshop-lists">
    <% @fashion.each do |shop| %>
    <div class="eachshop-list">
      <%= link_to image_tag(shop.images[0], class: :shop_image),shop_path(shop.id) %>
      <div class="eachshop-contents">
        <div class="eachshop-detail-name">
          <%= link_to "ショップ名：#{shop.shop_name}", shop_path(shop.id), class: :detail_link %>
        </div>
        <div class="eachshop-detail-introduction">
          <%= "ショップ詳細：#{shop.introduction}" %>
        </div>
        <div class="eachshop-detail-address">
          <%= "所在地：#{shop.prefecture.name}#{shop.shop_city.name}#{shop.shop_address}" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shops/food.html.erb
<%= render "shared/header" %>

<div class="eachshop-main">
  <h2 class="list-title">
    FOOD SHOP LIST
  </h2>
  <div class="eachshop-lists">
    <% @food.each do |shop| %>
    <div class="eachshop-list">
      <%= link_to image_tag(shop.images[0], class: :shop_image),shop_path(shop.id) %>
      <div class="eachshop-contents">
        <div class="eachshop-detail-name">
          <%= link_to "ショップ名：#{shop.shop_name}", shop_path(shop.id), class: :detail_link %>
        </div>
        <div class="eachshop-detail-introduction">
          <%= "ショップ詳細：#{shop.introduction}" %>
        </div>
        <div class="eachshop-detail-address">
          <%= "所在地：#{shop.prefecture.name}#{shop.shop_city.name}#{shop.shop_address}" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shops/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="main-inner">
    <div class="upper-part">
      <%= form_with(url: search_shop_path(:shop_id), local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "Shop search...", autocomplete: "off", class: "search-input" %>
        <%= form.submit "🔍", class: "search-btn" %>
      <% end %>
      <% if user_signed_in? %>
      <div class="log_chk">ようこそ
        <%= link_to "#{current_user.username}", user_path(current_user.id), class: :greeting__link %> さん
        <%= image_tag("niko.svg", class: :icon) %>
      </div>
      <% end %>
    </div>

    <%# スライダー %>
    <div class="container-zone">
      <div class="container">
        <div class="swiper infinite-slider">
          <div class="swiper-wrapper">
            <div class="swiper-slide">
              <%= image_tag "70BOSAKA.jpeg", alt: "画像1" %>
              <%= image_tag "SQUAREFURNITURE.jpeg", alt: "画像2" %>
              <%= image_tag "TRUCKFURNITURE.jpeg", alt: "画像3" %>
              <%= image_tag "Armonia.jpeg", alt: "画像4" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%# ピックアップ %>
    <div class="center">
      <div class="pickup-contents">
        <div class='service-title'>
          <p>New Shops</p>
        </div>

        <div class="top_menu">
          <%# 新着投稿 Fashion %>
          <div class="new_shops_genre">
            <%= link_to image_tag("Fashion.png", class: :fashion_interior_btn), fashion_shops_path %>
            <ul class="new_shops">
              <% @fashion.first(5).each do |shop| %>
                <li class="new_shop_contents">
                  <div class="new_shop_content">
                    <%= shop.created_at.strftime("%Y/%m/%d") %>
                  </div>
                  <div class="new_shop_content">
                    <%= link_to shop.shop_name, shop_path(shop.id), class: :detail_link %>
                  </div>
                  <div class="new_shop_content">
                    <%= shop.shop_city.name %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>

          <%# 新着投稿 Food %>
          <div class="new_shops_genre">
            <%= link_to image_tag("Food.png", class: :food_btn), food_shops_path %>
            <ul class="new_shops">
              <% @food.first(5).each do |shop| %>
                <li class="new_shop_contents">
                  <div class="new_shop_content">
                    <%= shop.created_at.strftime("%Y/%m/%d") %>
                  </div>
                  <div class="new_shop_content">
                    <%= link_to shop.shop_name, shop_path(shop.id), class: :detail_link %>
                  </div>
                  <div class="new_shop_content">
                    <%= shop.shop_city.name %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>

          <%# 新着投稿 Interior %>
          <div class="new_shops_genre">
            <%= link_to image_tag("Interior.png", class: :fashion_interior_btn), interior_shops_path %>
            <ul class="new_shops">
              <% @interior.first(5).each do |shop| %>
                <li class="new_shop_contents">
                  <div class="new_shop_content">
                    <%= shop.created_at.strftime("%Y/%m/%d") %>
                  </div>
                  <div class="new_shop_content">
                    <%= link_to shop.shop_name, shop_path(shop.id), class: :detail_link %>
                  </div>
                  <div class="new_shop_content">
                    <%= shop.shop_city.name %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>

        </div>
      </div>
    </div> 
  </div>
</div>
<%= render "shared/footer" %>

app/views/shops/interior.html.erb
<%= render "shared/header" %>

<div class="eachshop-main">
  <h2 class="list-title">
    INTERIOR SHOP LIST
  </h2>
  <div class="eachshop-lists">
    <% @interior.each do |shop| %>
    <div class="eachshop-list">
      <%= link_to image_tag(shop.images[0], class: :shop_image),shop_path(shop.id) %>
      <div class="eachshop-contents">
        <div class="eachshop-detail-name">
          <%= link_to "ショップ名：#{shop.shop_name}", shop_path(shop.id), class: :detail_link %>
        </div>
        <div class="eachshop-detail-introduction">
          <%= "ショップ詳細：#{shop.introduction}" %>
        </div>
        <div class="eachshop-detail-address">
          <%= "所在地：#{shop.prefecture.name}#{shop.shop_city.name}#{shop.shop_address}" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shops/show.html.erb
<%= render "shared/header" %>

<div class="shopdetails-main">
  <div class="shopdetails-inner">
    <h2 class="shopdetails-title">
      SHOP DETAILS
    </h2>
    <div class="shopdetail">
      <div class="detail-image">
        <%= image_tag @shop.images[0], class: 'detail_shop_image' %>
      </div>
      <div class="detail-contents">
        <% if user_signed_in? && current_user.id == @shop.user_id %>
        <div class="content-edit">
          <%= link_to image_tag("sozai_cman_jp_20220906191451.png", class: :setting_icon), edit_shop_path(@shop.id) %>
          <p class="fukidashi">編集</p>
        </div>
        <% end %>
        <div class="detail-name">
          <%= @shop.shop_name %>
        </div>
        <div class="details">
          <div class="detail-introduction">
            <%= @shop.introduction %><br>
          </div>
          <div class="detail-address">
            <span><%= image_tag("sozai_cman_jp_20220909150352.png", class: :position_icon) %></span>
            <%= @shop.prefecture.name %><%= @shop.shop_city.name %><%= @shop.shop_address %>
          </div>
          <div class="detail-user">
            <span>post by</span><%= link_to @shop.user.username, user_path(@shop.user.id) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%# 口コミ投稿&一覧 %>
  <div class="evaluation_container">

    <%# 口コミ投稿フォーム %>
    <div class="evaluation-inner">
      <div class="evaluation-title">
        クチコミを投稿する
      </div>
      <% if user_signed_in? %>
        <%= form_with(model: @comment, url: shop_evaluation_comments_path(@shop.id), local: true) do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

        <div class="form-parts">
          <div class="title-label">
            <%= f.label :title, 'タイトル', class:"title-label" %>
          </div>
          <%= f.text_field :title, placeholder:"(必須)", class: "title-form" %>
        </div>
        <div class="form-parts">
          <%= f.label :content, 'クチコミ内容', class:"content-label" %>
          <%= f.text_area :content, rows:'5', placeholder:"クチコミ内容がなくても、タイトルと評価のみで投稿できます", class: "content-form" %>
        </div>
        <div class="rating-form">  
          <div class="rating-star">評価</div>
          <%= f.hidden_field :rate %>
        </div>
        <%= f.submit "投稿", class:'evaluation-post-btn' %>
        <% end %>
      <% else %>
        <strong><p>※※※ クチコミの投稿には新規登録/ログインが必要です ※※※</p>
        </strong>
      <% end %>
      <%# /口コミ投稿フォーム %>
    </div>

    <%# 口コミ一覧 %>
    <div class="evaluation-inner">
      <div class="evaluation_comments">
        <div class="evaluation-comments-title">
          <%= @shop.shop_name %>  クチコミ一覧
        </div>
        
        <%# コメント繰り返し処理 %>
        <% @evaluation_comments.each do |comment| %>
          <div class="evaluation-lists">
            <div class="evaluation-group">
              <div class="evaluation-row">
                <div class="evaluation-list-name">
                  <%= link_to comment.user.username, "/users/#{comment.user_id}" %>
                </div>
                <div class="evaluation-list-title">
                  <%= comment.title %>
                </div>
                <div class="shop-evaluation" data-score="<%= comment.rate %>"></div>
                <div class="score-display">
                  （<%= comment.rate %>点）
                </div>

                <% if user_signed_in? && current_user.id == comment.user_id %>
                <div class="comment-delete-btn">
                  <%=link_to '削除', shop_evaluation_comment_path(@shop.id, comment.id), method: :delete, data: {confirm: "削除しますか？"} %>
                </div>
                <% end %>

              </div>
              <div class="evaluation-list-content">
                <%= comment.content %>
              </div>
            </div>
          </div>
        <% end %>
        <%# /コメント繰り返し処理 %>

      </div>
    </div>
    <%# /口コミ一覧 %>
  </div>
</div>

<%# クチコミ投稿の評価 %>
<script>
  $('.rating-form').raty({
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'evaluation_comment[rate]',
      half: true,
  });
</script>

<%# クチコミ一覧の評価 %>
<script>
  $('.shop-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="mypage-main">
  <div class="mypage-inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.username} さんの投稿一覧" %>
      </h2>
      <div class="mypage-lists">
        <% @shops.each do |shop| %>
          <div class="mypage-list">
            <%= link_to image_tag(shop.images[0], class: :mypage_shop_image),shop_path(shop.id) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>